<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="166" started-at="2023-06-18T23:27:55 IST" finished-at="2023-06-18T23:27:55 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="166" started-at="2023-06-18T23:27:55 IST" finished-at="2023-06-18T23:27:55 IST">
      <class name="testPackage.Test1">
        <test-method status="PASS" signature="tc1()[pri:0, instance:testPackage.Test1@49835d]" name="tc1" duration-ms="15" started-at="2023-06-18T23:27:55 IST" finished-at="2023-06-18T23:27:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc1 -->
        <test-method status="PASS" signature="tc2()[pri:0, instance:testPackage.Test1@49835d]" name="tc2" duration-ms="0" started-at="2023-06-18T23:27:55 IST" finished-at="2023-06-18T23:27:55 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc2 -->
        <test-method status="FAIL" signature="tc3()[pri:0, instance:testPackage.Test1@49835d]" name="tc3" duration-ms="5" started-at="2023-06-18T23:27:55 IST" finished-at="2023-06-18T23:27:55 IST">
          <exception class="java.lang.IllegalArgumentException">
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException
at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:254)
at java.util.concurrent.ArrayBlockingQueue.<init>(ArrayBlockingQueue.java:239)
at pck1.RecentlyPlayed.<init>(RecentlyPlayed.java:11)
at testPackage.Test1.tc3(Test1.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc3 -->
      </class> <!-- testPackage.Test1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
